OnlineRecruitingPlatform.DevExtremeAspNetCore/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineRecruitingPlatform.DevExtremeAspNetCore.Models;
using OnlineRecruitingPlatform.Model.Deserializers;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HeadHunterClients = OnlineRecruitingPlatform.HttpClients.HeadHunter.Clients;
using HeadHunterCompanies = OnlineRecruitingPlatform.Model.API.HeadHunter.Companies;
using ZarplataRu = OnlineRecruitingPlatform.Model.API.ZarplataRu;
using ZarplataRuClients = OnlineRecruitingPlatform.HttpClients.ZarplataRu.Clients;

namespace OnlineRecruitingPlatform.DevExtremeAspNetCore.Controllers
{
    public class CompanyController : Controller
    {
        private readonly HeadHunterClients.Companies.CompaniesClient _companiesHeadHunterClient;
        private readonly ZarplataRuClients.Companies.CompaniesClient _companiesZarplataRuClient;

        public CompanyController(HeadHunterClients.Companies.CompaniesClient companiesHeadHunterClient, ZarplataRuClients.Companies.CompaniesClient companiesZarplataRuClient)
        {
            _companiesHeadHunterClient = companiesHeadHunterClient;
            _companiesZarplataRuClient = companiesZarplataRuClient;
        }

        [Route("~/Company")]
        [Route("~/Company/Browse")]
        public async Task<IActionResult> Browse()
        {
            var resultCompaniesHeadHunter = await BaseDeserializer.Deserialize<HeadHunterCompanies.SearchResultCompanies>(await _companiesHeadHunterClient.GetCompanies(1, 25));
            var resultCompaniesZarplataRu = await GzipDeserializer.Deserialize<ZarplataRu.CompaniesDirectory>(await _companiesZarplataRuClient.GetCompanies(25, 1));

            var viewModel = new BrowseCompaniesViewModel()
            {
                NumberPage = 1,
                SearchStringByTitle = "",
                SearchStringByLocation = "",
                CompaniesHeadHunter = resultCompaniesHeadHunter.Companies.ToList(),
                CompaniesZarplataRu = resultCompaniesZarplataRu.Companies.ToList(),
                CountItems = resultCompaniesHeadHunter.Found + resultCompaniesZarplataRu.Metadata.Resultset.Count
            };

            viewModel.GeneratePagination();

            return View(viewModel);
        }

        [HttpPost]
        [Route("~/Company/Browse")]
        public async Task<IActionResult> Browse(BrowseCompaniesViewModel viewModel)
        {
            var resultCompaniesHeadHunter = await BaseDeserializer.Deserialize<HeadHunterCompanies.SearchResultCompanies>(await _companiesHeadHunterClient.GetCompanies(viewModel.NumberPage, 25, viewModel.SearchStringByTitle, viewModel.SearchStringByLocation));
            var resultCompaniesZarplataRu = await GzipDeserializer.Deserialize<ZarplataRu.CompaniesDirectory>(await _companiesZarplataRuClient.GetCompanies(25, viewModel.NumberPage * 25, viewModel.SearchStringByTitle, viewModel.SearchStringByLocation));

            if (resultCompaniesHeadHunter == null)
            {
                resultCompaniesHeadHunter = new HeadHunterCompanies.SearchResultCompanies()
                {
                    Found = 0,
                    Companies = new List<dynamic>().ToArray()
                };
            }

            if (resultCompaniesZarplataRu == null)
            {
                resultCompaniesZarplataRu = new ZarplataRu.CompaniesDirectory()
                {
                    Metadata = new ZarplataRu.Metadata()
                    {
                        Resultset = new ZarplataRu.Resultset()
                        {
                            Count = 0
                        }
                    },
                    Companies = new List<dynamic>().ToArray()
                };
            }

            viewModel.CompaniesHeadHunter = resultCompaniesHeadHunter.Companies.ToList();
            viewModel.CompaniesZarplataRu = resultCompaniesZarplataRu.Companies.ToList();
            viewModel.CountItems = resultCompaniesHeadHunter.Found + resultCompaniesZarplataRu.Metadata.Resultset.Count;
            viewModel.GeneratePagination();

            return View(viewModel);
        }

        [Route("~/Company/{type}/{id}")]
        public async Task<IActionResult> Details(string type, int id)
        {
            if (type == "HeadHunter")
            {
                return View("DetailsCompanyHeadHunter", await BaseDeserializer.Deserialize<dynamic>(await _companiesHeadHunterClient.GetCompany(id)));
            }

            if (type == "ZarplataRu")
            {
                var result = await GzipDeserializer.Deserialize<dynamic>(await _companiesZarplataRuClient.GetCompany(id));

                return View("DetailsCompanyZarplataRu", result.companies[0]);
            }

            return View("DetailsCompany");
        }
    }
}

OnlineRecruitingPlatform.DevExtremeAspNetCore/Controllers/ResumeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineRecruitingPlatform.DevExtremeAspNetCore.Models;
using OnlineRecruitingPlatform.Model.Deserializers;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZarplataRu = OnlineRecruitingPlatform.Model.API.ZarplataRu;
using ZarplataRuClients = OnlineRecruitingPlatform.HttpClients.ZarplataRu.Clients;

namespace OnlineRecruitingPlatform.DevExtremeAspNetCore.Controllers
{
    public class ResumeController : Controller
    {
        private readonly ZarplataRuClients.Resumes.ResumesClient _resumesZarplataRuClient;

        public ResumeController(ZarplataRuClients.Resumes.ResumesClient resumesZarplataRuClient)
        {
            _resumesZarplataRuClient = resumesZarplataRuClient;
        }

        [Route("~/Resume")]
        [Route("~/Resume/Browse")]
        public async Task<IActionResult> Browse()
        {
            var resultResumesZarplataRu = await GzipDeserializer.Deserialize<ZarplataRu.ResumesDirectory>(await _resumesZarplataRuClient.GetResumes(25, 0));

            var viewModel = new BrowseResumesViewModel()
            {
                NumberPage = 1,
                SearchStringByCityAddressOrZip = "",
                SearchStringByJobTitleSkills = "",
                ResumesZarplataRu = resultResumesZarplataRu.Resumes.ToList(),
                CountItems = resultResumesZarplataRu.Metadata.Resultset.Count
            };

            viewModel.GeneratePagination();

            return View(viewModel);
        }

        [HttpPost]
        [Route("~/Resume/Browse")]
        public async Task<IActionResult> Browse(BrowseResumesViewModel viewModel)
        {
            var resultResumesZarplataRu = await GzipDeserializer.Deserialize<ZarplataRu.ResumesDirectory>(await _resumesZarplataRuClient.GetResumes(25, viewModel.NumberPage * 25, viewModel.SearchStringByJobTitleSkills, viewModel.SearchStringByCityAddressOrZip));

            if (resultResumesZarplataRu == null)
            {
                resultResumesZarplataRu = new ZarplataRu.ResumesDirectory()
                {
                    Metadata = new ZarplataRu.Metadata()
                    {
                        Resultset = new ZarplataRu.Resultset()
                        {
                            Count = 0
                        }
                    },
                    Resumes = new List<dynamic>().ToArray()
                };
            }

            viewModel.ResumesZarplataRu = resultResumesZarplataRu.Resumes.ToList();
            viewModel.CountItems = resultResumesZarplataRu.Metadata.Resultset.Count;
            viewModel.GeneratePagination();

            return View(viewModel);
        }

        [Route("~/Resume/{type}/{id}")]
        public async Task<IActionResult> Details(string type, int id)
        {
            if (type == "ZarplataRu")
            {
                var result = await GzipDeserializer.Deserialize<dynamic>(await _resumesZarplataRuClient.GetResume(id));

                return View("DetailsResumeZarplataRu", result.resumes[0]);
            }

            return View("DetailsResume");
        }
    }
}

OnlineRecruitingPlatform.DevExtremeAspNetCore/Controllers/VacancyController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineRecruitingPlatform.DevExtremeAspNetCore.Models;
using OnlineRecruitingPlatform.Model.Deserializers;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HeadHunterClients = OnlineRecruitingPlatform.HttpClients.HeadHunter.Clients;
using HeadHunterVacancies = OnlineRecruitingPlatform.Model.API.HeadHunter.Vacancies;
using ZarplataRu = OnlineRecruitingPlatform.Model.API.ZarplataRu;
using ZarplataRuClients = OnlineRecruitingPlatform.HttpClients.ZarplataRu.Clients;

namespace OnlineRecruitingPlatform.DevExtremeAspNetCore.Controllers
{
    public class VacancyController : Controller
    {
        private readonly HeadHunterClients.Vacancies.VacanciesClient _vacanciesHeadHunterClient;
        private readonly ZarplataRuClients.Vacancies.VacanciesClient _vacanciesZarplataRuClient;

        public VacancyController(HeadHunterClients.Vacancies.VacanciesClient vacanciesHeadHunterClient, ZarplataRuClients.Vacancies.VacanciesClient vacanciesZarplataRuClient)
        {
            _vacanciesHeadHunterClient = vacanciesHeadHunterClient;
            _vacanciesZarplataRuClient = vacanciesZarplataRuClient;
        }

        [Route("~/Vacancy")]
        [Route("~/Vacancy/Browse")]
        public async Task<IActionResult> Browse()
        {
            var resultVacanciesHeadHunter = await BaseDeserializer.Deserialize<HeadHunterVacancies.VacanciesDirectory>(await _vacanciesHeadHunterClient.GetVacancies(25, 1));
            var resultVacanciesZarplataRu = await GzipDeserializer.Deserialize<ZarplataRu.VacanciesDirectory>(await _vacanciesZarplataRuClient.GetVacancies(25, 1));

            var viewModel = new BrowseVacanciesViewModel()
            {
                NumberPage = 1,
                SearchStringByCityAddressOrZip = "",
                SearchStringByJobTitleSkillsOrCompany = "",
                VacanciesHeadHunter = resultVacanciesHeadHunter.Vacancies.ToList(),
                VacanciesZarplataRu = resultVacanciesZarplataRu.Vacancies.ToList(),
                CountItems = resultVacanciesHeadHunter.Found + resultVacanciesZarplataRu.Metadata.Resultset.Count
            };

            viewModel.GeneratePagination();

            return View(viewModel);
        }

        [Route("~/Vacancy/Browse/{title}")]
        public async Task<IActionResult> Browse(string title)
        {
            var resultVacanciesHeadHunter = await BaseDeserializer.Deserialize<HeadHunterVacancies.VacanciesDirectory>(await _vacanciesHeadHunterClient.GetVacancies(25, 1, title));
            var resultVacanciesZarplataRu = await GzipDeserializer.Deserialize<ZarplataRu.VacanciesDirectory>(await _vacanciesZarplataRuClient.GetVacancies(25, 1, title));

            var viewModel = new BrowseVacanciesViewModel()
            {
                NumberPage = 1,
                SearchStringByCityAddressOrZip = "",
                SearchStringByJobTitleSkillsOrCompany = title,
                VacanciesHeadHunter = resultVacanciesHeadHunter.Vacancies.ToList(),
                VacanciesZarplataRu = resultVacanciesZarplataRu.Vacancies.ToList(),
                CountItems = resultVacanciesHeadHunter.Found + resultVacanciesZarplataRu.Metadata.Resultset.Count
            };

            viewModel.GeneratePagination();

            return View(viewModel);
        }

        [HttpPost]
        [Route("~/Vacancy/Browse")]
        public async Task<IActionResult> Browse(BrowseVacanciesViewModel viewModel)
        {
            var resultVacanciesHeadHunter = await BaseDeserializer.Deserialize<HeadHunterVacancies.VacanciesDirectory>(await _vacanciesHeadHunterClient.GetVacancies(25, viewModel.NumberPage, viewModel.SearchStringByJobTitleSkillsOrCompany, viewModel.SearchStringByCityAddressOrZip));
            var resultVacanciesZarplataRu = await GzipDeserializer.Deserialize<ZarplataRu.VacanciesDirectory>(await _vacanciesZarplataRuClient.GetVacancies(25, viewModel.NumberPage * 25, viewModel.SearchStringByJobTitleSkillsOrCompany, viewModel.SearchStringByCityAddressOrZip));

            if(resultVacanciesHeadHunter == null)
            {
                resultVacanciesHeadHunter = new HeadHunterVacancies.VacanciesDirectory()
                {
                    Found = 0,
                    Vacancies = new List<dynamic>().ToArray()
                };
            }

            if (resultVacanciesZarplataRu == null)
            {
                resultVacanciesZarplataRu = new ZarplataRu.VacanciesDirectory()
                {
                    Metadata = new ZarplataRu.Metadata()
                    {
                        Resultset = new ZarplataRu.Resultset()
                        {
                            Count = 0
                        }
                    },
                    Vacancies = new List<dynamic>().ToArray()
                };
            }

            viewModel.VacanciesHeadHunter = resultVacanciesHeadHunter.Vacancies.ToList();
            viewModel.VacanciesZarplataRu = resultVacanciesZarplataRu.Vacancies.ToList();
            viewModel.CountItems = resultVacanciesHeadHunter.Found + resultVacanciesZarplataRu.Metadata.Resultset.Count;
            viewModel.GeneratePagination();

            return View(viewModel);
        }

        [HttpPost]
        [Route("~/Vacancy")]
        public async Task<IActionResult> Browse(HomeViewModel homeViewModel)
        {
            var resultVacanciesHeadHunter = await BaseDeserializer.Deserialize<HeadHunterVacancies.VacanciesDirectory>(await _vacanciesHeadHunterClient.GetVacancies(25, 1, homeViewModel.SearchStringByJobTitleSkillsOrCompany));
            var resultVacanciesZarplataRu = await GzipDeserializer.Deserialize<ZarplataRu.VacanciesDirectory>(await _vacanciesZarplataRuClient.GetVacancies(25, 1, homeViewModel.SearchStringByJobTitleSkillsOrCompany));

            var viewModel = new BrowseVacanciesViewModel()
            {
                NumberPage = 1,
                VacanciesHeadHunter = resultVacanciesHeadHunter.Vacancies.ToList(),
                VacanciesZarplataRu = resultVacanciesZarplataRu.Vacancies.ToList(),
                SearchStringByCityAddressOrZip = homeViewModel.SearchStringByCityAddressOrZip,
                SearchStringByJobTitleSkillsOrCompany = homeViewModel.SearchStringByJobTitleSkillsOrCompany,
                CountItems = resultVacanciesHeadHunter.Found + resultVacanciesZarplataRu.Metadata.Resultset.Count
            };

            viewModel.GeneratePagination();

            return View(viewModel);
        }

        [Route("~/Vacancy/{type}/{id}")]
        public async Task<IActionResult> Details(string type, int id)
        {
            if(type == "HeadHunter")
            {
                return View("DetailsVacancyHeadHunter", await BaseDeserializer.Deserialize<dynamic>(await _vacanciesHeadHunterClient.GetVacancy(id)));
            }

            if(type == "ZarplataRu")
            {
                var result = await GzipDeserializer.Deserialize<dynamic>(await _vacanciesZarplataRuClient.GetVacancy(id));

                return View("DetailsVacancyZarplataRu", result.vacancies[0]);
            }

            return View("DetailsVacancy");
        }
    }
}

OnlineRecruitingPlatform.DevExtremeAspNetCore/Views/Shared/CssPartial.cshtml
<link href="http://fonts.googleapis.com/css?family=Oswald:100,300,400,500,600,800%7COpen+Sans:300,400,500,600,700,800%7CMontserrat:400,700" rel="stylesheet">
<link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true">

OnlineRecruitingPlatform.DevExtremeAspNetCore/Views/Shared/FooterPartial.cshtml
<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h6>О нас</h6>
                <p class="text-justify">Веб-сайт по трудоустройству - это веб-сайт, специально посвященный вопросам трудоустройства или карьеры. Многие веб-сайты по трудоустройству предназначены для того, чтобы работодатели могли публиковать требования к вакансиям, которые необходимо заполнить, и обычно называются досками по трудоустройству. Другие сайты по трудоустройству предлагают обзоры работодателей, советы по карьере и поиску работы, а также описывают различные описания должностей или работодателей. Через веб-сайт о вакансиях потенциальный сотрудник может найти и заполнить заявление о приеме на работу.</p>
            </div>
            @*<div class="col-xs-6 col-md-3">
                <h6>Компания</h6>
                <ul class="footer-links">
                    <li><a href="page-about.html">О нас</a></li>
                    <li><a href="page-typography.html">Как это работает</a></li>
                    <li><a href="page-typography.html">Политика конфиденциальности</a></li>
                    <li><a href="page-contact.html">Свяжитесь с нами</a></li>
                </ul>
            </div>*@
            <div class="col-xs-6 col-md-3">
                <h6>Актуальные вакансии</h6>
                <ul class="footer-links">
                    <li><a asp-controller="Vacancy" asp-action="Browse" asp-route-title="Front-end developer">Front-end developer</a></li>
                    <li><a asp-controller="Vacancy" asp-action="Browse" asp-route-title="Android developer">Android developer</a></li>
                    <li><a asp-controller="Vacancy" asp-action="Browse" asp-route-title="iOS developer">iOS developer</a></li>
                    <li><a asp-controller="Vacancy" asp-action="Browse" asp-route-title="Full stack developer">Full stack developer</a></li>
                    <li><a asp-controller="Vacancy" asp-action="Browse" asp-route-title="Project administrator">Project administrator</a></li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
</footer>

OnlineRecruitingPlatform.DevExtremeAspNetCore/Views/Shared/HeaderPartial.cshtml
@using OnlineRecruitingPlatform.Model.Formatters.String
@model OnlineRecruitingPlatform.DevExtremeAspNetCore.Models.HomeViewModel
<header class="site-header size-lg text-center" style="background-image: url(images/interface/main/bg-banner1.jpg)">
    <div class="container">
        <div class="col-xs-12">
            <br><br>
            <h2>Мы предлагаем <mark>@Model.CountActiveVacancies</mark> @(Declension.DeclensionByNumeral(Model.CountActiveVacancies, new string[3] 
                                                                       {
                                                                            "вакансия",
                                                                            "вакансий",
                                                                            "вакансий"
                                                                        }, false)) прямо сейчас!</h2>
            <h5 class="font-alt">Найдите свое желание за минуту</h5>
            <br><br><br>
            <form class="header-job-search" method="post" asp-controller="Vacancy">
                <div class="input-keyword">
                    <input type="text" class="form-control" placeholder="Должность, навыки или компания" asp-for="SearchStringByJobTitleSkillsOrCompany">
                </div>

                <div class="input-location">
                    <input type="text" class="form-control" placeholder="Город, область или почтовый индекс" asp-for="SearchStringByCityAddressOrZip">
                </div>

                <div class="btn-search">
                    <button class="btn btn-primary" type="submit">Найти работу</button>
                    <a href="job-list.html">Расширенный поиск работы</a>
                </div>
            </form>
        </div>

    </div>
</header>

OnlineRecruitingPlatform.DevExtremeAspNetCore/Views/Shared/IconPartial.cshtml
<link rel="apple-touch-icon" href="~/images/logo/logo.ico">
<link rel="icon" href="~/images/logo/logo.ico">

OnlineRecruitingPlatform.DevExtremeAspNetCore/Views/Shared/MetatagsPartial.cshtml
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Post a job position or create your online resume by TheJobs!">
<meta name="keywords" content="">

OnlineRecruitingPlatform.DevExtremeAspNetCore/Views/Shared/NavBarPartial.cshtml
<nav class="navbar">
    <div class="container">
        <div class="pull-left">
            <a class="navbar-toggle" href="#" data-toggle="offcanvas">
                <i class="ti-menu"></i>
            </a>
            <div class="logo-wrapper">
                <a class="logo" asp-controller="Home" asp-action="Index"><img src="~/images/logo/logo.ico" alt="logo"></a>
                <a class="logo-alt" asp-controller="Home" asp-action="Index"><img src="~/images/logo/logo.ico" alt="logo-alt"></a>
            </div>
        </div>
        <ul class="nav-menu">
            <li>
                <a asp-controller="Home" asp-action="Index">Главная</a>
            </li>
            <li>
                <a asp-controller="Vacancy" asp-action="Browse">Вакансии</a>
            </li>
            <li>
                <a asp-controller="Resume" asp-action="Browse">Резюме</a>
            </li>
            <li>
                <a asp-controller="Company" asp-action="Browse">Компании</a>
            </li>
        </ul>
    </div>
</nav>

OnlineRecruitingPlatform.DevExtremeAspNetCore/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/main/app.min.js"></script>
<script src="~/js/main/custom.js"></script>

OnlineRecruitingPlatform.DevExtremeAspNetCore/Views/Shared/TitlePartial.cshtml
<title>TheJobs</title>

OnlineRecruitingPlatform.DevExtremeAspNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("TitlePartial")
    @await Html.PartialAsync("IconPartial")
    @await Html.PartialAsync("CssPartial")
    @await Html.PartialAsync("ScriptsPartial")
</head>
<body class="nav-on-header">
    @await Html.PartialAsync("NavBarPartial")
    @RenderBody()
    @await Html.PartialAsync("FooterPartial")
    <a id="scroll-up" href="#">
        <i class="ti-angle-up"></i>
    </a>
    @if (IsSectionDefined("ScriptPage"))
    {
        @await RenderSectionAsync("ScriptPage")
    }
</body>
</html>